### ISSUE TITLE
Mobile issue

### ISSUE THREAD

**Issue by lispberry** [skeeto/skeeto.github.com#5]
![image](https://user-images.githubusercontent.com/14040430/39979060-7b3f0740-575d-11e8-8c95-a06210cc62ad.png)

The problem has to do with a long link in the article "A Crude Personal Package Manager": browsers consider it to be a word.

Possible fix:
```css
main {
    word-wrap: break-word;
}
```

Thank you for the content you make. I've enjoyed reading your blog a lot.

**Comment by skeeto** [comment]
Thanks for the heads up! I primarily use Firefox, and, unlike Chrome, it 
seems Firefox word breaks on slashes by default, so it didn't need 
permission to break the long URL. I went with your suggested fix. In the 
future I'll probably avoid displaying long URLs like this.
